package com.platform.backend.entity;

import lombok.Data;
//import org.apache.ibatis.type.Alias;

import java.util.Date;

//@Alias("backendUser")
public class BackendUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.id
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.user_code
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.user_name
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.user_type
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Long userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.created_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.creation_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.modify_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Long modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.modify_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_backend_user.user_password
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.id
     *
     * @return the value of t_backend_user.id
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.id
     *
     * @param id the value for t_backend_user.id
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.user_code
     *
     * @return the value of t_backend_user.user_code
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.user_code
     *
     * @param userCode the value for t_backend_user.user_code
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.user_name
     *
     * @return the value of t_backend_user.user_name
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.user_name
     *
     * @param userName the value for t_backend_user.user_name
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.user_type
     *
     * @return the value of t_backend_user.user_type
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Long getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.user_type
     *
     * @param userType the value for t_backend_user.user_type
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setUserType(Long userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.created_by
     *
     * @return the value of t_backend_user.created_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.created_by
     *
     * @param createdBy the value for t_backend_user.created_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.creation_date
     *
     * @return the value of t_backend_user.creation_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.creation_date
     *
     * @param creationDate the value for t_backend_user.creation_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.modify_by
     *
     * @return the value of t_backend_user.modify_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.modify_by
     *
     * @param modifyBy the value for t_backend_user.modify_by
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.modify_date
     *
     * @return the value of t_backend_user.modify_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.modify_date
     *
     * @param modifyDate the value for t_backend_user.modify_date
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_backend_user.user_password
     *
     * @return the value of t_backend_user.user_password
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_backend_user.user_password
     *
     * @param userPassword the value for t_backend_user.user_password
     *
     * @mbggenerated Sat Oct 29 11:15:54 CST 2022
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    @Override
    public String toString() {
        return "BackendUser{" +
                "id=" + id +
                ", userCode='" + userCode + '\'' +
                ", userName='" + userName + '\'' +
                ", userType=" + userType +
                ", createdBy=" + createdBy +
                ", creationDate=" + creationDate +
                ", modifyBy=" + modifyBy +
                ", modifyDate=" + modifyDate +
                ", userPassword='" + userPassword + '\'' +
                '}';
    }

}