package com.platform.backend.mapper;

import com.platform.backend.entity.Dictionary;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    Dictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dictionary
     *
     * @mbggenerated Mon Oct 31 08:57:27 CST 2022
     */
    int updateByPrimaryKey(Dictionary record);

    /**
     * 根据根据id查询字典
     */
    Dictionary selectByValueId(@Param("valueId") Long valueId);

    /**
     * 根据type_code查询数据字典
     */
    List<Dictionary> selectByTypeCodeDictionaryList(String typeCode);

}